#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#
PROJECT_NAME := ota_example_mqtt

export ESP_ALIYUN_PATH := $(realpath ../../../)
export IE_PATH ?= $(ESP_ALIYUN_PATH)/iotkit-embedded

EXTRA_COMPONENT_DIRS := $(realpath ../../../)

include $(IDF_PATH)/make/project.mk
